### ISSUE TITLE
Wrong number in table 5

### ISSUE THREAD

**Issue by Tobias-Georg** [sethfischer/nissan-leaf-obd-manual#6]
Hi,
thanks for sharing this odb information - really appreciated!
I think there is a small typo: in the first column of table 5, see https://leaf-obd.readthedocs.io/en/latest/pid/5b3.html#pid-5b3, it should be 5B3 instead of 3B3. Correct?

**Comment by sethfischer** [comment]
Thanks @Tobias-Georg you're correct. It should be 5B3 instead of 3B3.
